version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: report_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: reports
      POSTGRES_PASSWORD: reports
      POSTGRES_DB: reports
    volumes:
      - ./.docker:/var/lib/postgresql/data
