version: "3.8"

services:
  report-viewer-database:
    image: postgres:16.2
    container_name: report_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: reports
      POSTGRES_PASSWORD: reports
      POSTGRES_DB: reports
    volumes:
      - ./.docker:/var/lib/postgresql/data
    networks:
      - report-viewer-network
  report-viewer-client:
    build:
      context: ./web
    ports:
      - "3001:3000"
    restart: "no"
    environment:
      - NODE_ENV=production
    networks:
      - report-viewer-network

  report-viewer-api:
    build:
      context: ./service
    ports:
      - "3000:3000"
    restart: "no"
    environment:
      - NODE_ENV=production
      - POSTGRES_URL=postgres://reports:reports@report_db:5432/reports
    networks:
      - report-viewer-network

networks:
  report-viewer-network:
    driver: bridge
